import type { Metadata } from "next";
import { Parkinsans } from "next/font/google";
import "./globals.css";
import "./hover.css"
import "bootstrap-icons/font/bootstrap-icons.css"
import { LanguageProvider } from "@/context/LanguageContext";

const parkinsans = Parkinsans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${parkinsans.className}`}
      >
        <LanguageProvider>
          {children}
        </LanguageProvider>
      </body>
    </html>
  );
}
